export const USER_SIGNIN_API = 'USER_SIGNIN_API';

export const US_LOGIN = 'US_LOGIN';

// projectCategory

export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";
export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";

//get all project
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';